title: Goseongjin's Blog
email: tjdwls9267@naver.com
description: >-
  안녕하십니까, 고성진의 깃허브 블로그입니다.
baseurl: "" 
url: "https://goseongjin.github.io"
twitter_username: ""
github_username: goseongjin

remote_theme: pages-themes/hacker@v0.2.0

plugins: 
  - jekyll-remote_theme
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO 관련
author: Goseongjin
lang: ko
logo: /assets/images/logo.png # 로고를 사용한다면 추가
google_analytics: UA-XXXXXXXXX-X # 추적코드 있으면 입력

# Markdown 스타일 개선
markdown: kramdown
kramdown:
  input: GFM
